### ISSUE TITLE
can't yank to system clipboard

### ISSUE THREAD

**Issue by AndreGeng** [thornycrackers/docker-neovim#1]
awesome repo, just wondering, is there a way to yank to host machine's system clipboard, when using this dockerized neovim

**Comment by thornycrackers** [comment]
Hey! Thanks for taking an interest!

The easiest way is to expose your clipboard over a port an have the dockerized neovim send the text over the network. A simple way to demonstrate how this can work is start a container:
```
docker run --rm -it --network host ubuntu:18.04 bash
```
Run netcat on your local machine in another terminal:
```
nc -l 8000
```
Then in the container install netcat and send some text
```
apt-get update && apt-get install netcat
echo 'hi' | netcat 127.0.0.1 8000
```
And then you should see the text come through to your local terminal. Once you've confirmed that you can indeed send text from the container then the next step is to use something like clipper https://github.com/wincent/clipper or another related service that exposes the clipboard on a port to accept that text and place it in your clipboard.

**Comment by AndreGeng** [comment]
Thanks for the response, I will try to see whether I can setup it correctly.
